# Generated by Django 2.2.17 on 2021-01-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('flaticon-themeforest', 'themeforest'), ('flaticon-dribbble', 'dribbble'), ('flaticon-behance-logo', 'behance'), ('flaticon-github-logo', 'github'), ('flaticon-flickr-website-logo-silhouette', 'flickr'), ('flaticon-smug', 'smug'), ('flaticon-squarespace-logo', 'squarespace'), ('flaticon-bitbucket-logotype-camera-lens-in-perspective', 'bitbucket')], max_length=55, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('habilidade', models.CharField(max_length=100, verbose_name='Habilidade')),
                ('nivel', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
    ]
